# Generated by Django 4.2.25 on 2025-10-02 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("descriptive", "Analyse Descriptive"),
                            ("correlation", "Analyse de Corrélation"),
                            ("regression", "Régression"),
                            ("clustering", "Clustering"),
                            ("timeseries", "Série Temporelle"),
                            ("custom", "Personnalisée"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("results", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("completed", "Terminée"),
                            ("failed", "Échouée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file_path", models.FileField(upload_to="datasets/")),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("json", "JSON"),
                            ("api", "API"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=False)),
                ("rows_count", models.IntegerField(blank=True, null=True)),
                ("columns_count", models.IntegerField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="Visualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("line", "Graphique en ligne"),
                            ("bar", "Graphique en barres"),
                            ("scatter", "Nuage de points"),
                            ("pie", "Graphique circulaire"),
                            ("histogram", "Histogramme"),
                            ("heatmap", "Carte de chaleur"),
                            ("box", "Boîte à moustaches"),
                        ],
                        max_length=20,
                    ),
                ),
                ("chart_config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.analysis",
                    ),
                ),
            ],
        ),
    ]
