# Generated by Django 4.2.7 on 2025-10-02 12:52

from django.db import migrations
# Remplacez XXXX par le numéro de votre migration
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),  # Remplacez par votre dernière migration
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='chart_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='visualization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visualization',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]