# Generated by Django 4.2.7 on 2025-10-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_auto_20251002_1252"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visualization", options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="visualization",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visualizations",
                to="analytics.analysis",
            ),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("line", "Graphique en ligne"),
                    ("bar", "Graphique en barres"),
                    ("scatter", "Nuage de points"),
                    ("pie", "Graphique circulaire"),
                    ("histogram", "Histogramme"),
                    ("heatmap", "Carte de chaleur"),
                    ("box", "Boîte à moustaches"),
                    ("correlation_matrix", "Matrice de corrélation"),
                    ("distribution", "Distribution"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="visualization", table="analytics_visualization",
        ),
    ]
