# Generated by Django 4.2.7 on 2025-10-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_alter_visualization_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visualization",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Visualisation",
                "verbose_name_plural": "Visualisations",
            },
        ),
        migrations.AddField(
            model_name="visualization",
            name="background_color",
            field=models.CharField(
                default="#ffffff", max_length=7, verbose_name="Couleur de fond"
            ),
        ),
        migrations.AddField(
            model_name="visualization",
            name="downloads_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de téléchargements"
            ),
        ),
        migrations.AddField(
            model_name="visualization",
            name="height",
            field=models.PositiveIntegerField(default=500, verbose_name="Hauteur"),
        ),
        migrations.AddField(
            model_name="visualization",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Mis en avant"),
        ),
        migrations.AddField(
            model_name="visualization",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("published", "Publié"),
                    ("archived", "Archivé"),
                ],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="visualization",
            name="tags",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="Tags (séparés par des virgules)",
            ),
        ),
        migrations.AddField(
            model_name="visualization",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre de vues"),
        ),
        migrations.AddField(
            model_name="visualization",
            name="width",
            field=models.PositiveIntegerField(default=800, verbose_name="Largeur"),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="chart_config",
            field=models.JSONField(default=dict, verbose_name="Configuration"),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="chart_data",
            field=models.JSONField(default=dict, verbose_name="Données"),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("line", "Graphique en ligne"),
                    ("bar", "Graphique en barres"),
                    ("horizontalBar", "Barres horizontales"),
                    ("scatter", "Nuage de points"),
                    ("pie", "Graphique circulaire"),
                    ("doughnut", "Graphique en anneau"),
                    ("radar", "Graphique radar"),
                    ("polarArea", "Zone polaire"),
                    ("histogram", "Histogramme"),
                    ("heatmap", "Carte de chaleur"),
                    ("box", "Boîte à moustaches"),
                    ("violin", "Graphique violon"),
                    ("correlation_matrix", "Matrice de corrélation"),
                    ("distribution", "Distribution"),
                    ("treemap", "Treemap"),
                    ("sunburst", "Sunburst"),
                ],
                max_length=20,
                verbose_name="Type de graphique",
            ),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Public"),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
        migrations.AddIndex(
            model_name="visualization",
            index=models.Index(
                fields=["chart_type"], name="analytics_v_chart_t_29e040_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visualization",
            index=models.Index(fields=["status"], name="analytics_v_status_c56f08_idx"),
        ),
        migrations.AddIndex(
            model_name="visualization",
            index=models.Index(
                fields=["is_public"], name="analytics_v_is_publ_f443a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visualization",
            index=models.Index(
                fields=["created_at"], name="analytics_v_created_31c41e_idx"
            ),
        ),
        migrations.AlterModelTable(name="visualization", table=None,),
    ]
