# Generated by Django 4.2.7 on 2025-10-02 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0005_alter_visualization_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatAnalyticsPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("prompt_template", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("descriptive", "Statistiques descriptives"),
                            ("correlation", "Analyse de corrélation"),
                            ("regression", "Régression"),
                            ("classification", "Classification"),
                            ("clustering", "Clustering"),
                            ("timeseries", "Séries temporelles"),
                            ("visualization", "Visualisation"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=50,
                    ),
                ),
                ("requires_target_column", models.BooleanField(default=False)),
                ("requires_feature_columns", models.BooleanField(default=False)),
                ("min_numeric_columns", models.PositiveIntegerField(default=0)),
                ("min_categorical_columns", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["category", "name"],},
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Utilisateur"),
                            ("assistant", "Assistant"),
                            ("system", "Système"),
                            ("function", "Fonction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Texte"),
                            ("analysis", "Analyse"),
                            ("visualization", "Visualisation"),
                            ("code", "Code"),
                            ("error", "Erreur"),
                            ("data_summary", "Résumé de données"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("structured_data", models.JSONField(blank=True, default=dict)),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                ("user_feedback", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Message de Chat",
                "verbose_name_plural": "Messages de Chat",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Nouvelle conversation", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "model_used",
                    models.CharField(default="gpt-4-turbo-preview", max_length=50),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        default="Vous êtes un assistant expert en analyse de données."
                    ),
                ),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("analysis_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Session de Chat",
                "verbose_name_plural": "Sessions de Chat",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DataAnalysisQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField()),
                ("analysis_type", models.CharField(max_length=50)),
                ("python_code", models.TextField()),
                (
                    "execution_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("results", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("execution_time", models.FloatField(blank=True, null=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.AlterModelOptions(
            name="visualization", options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="visualization", name="analytics_v_chart_t_29e040_idx",
        ),
        migrations.RemoveIndex(
            model_name="visualization", name="analytics_v_status_c56f08_idx",
        ),
        migrations.RemoveIndex(
            model_name="visualization", name="analytics_v_is_publ_f443a2_idx",
        ),
        migrations.RemoveIndex(
            model_name="visualization", name="analytics_v_created_31c41e_idx",
        ),
        migrations.AlterField(
            model_name="visualization",
            name="background_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="chart_config",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="chart_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("line", "Graphique en ligne"),
                    ("bar", "Graphique en barres"),
                    ("scatter", "Nuage de points"),
                    ("pie", "Graphique circulaire"),
                    ("doughnut", "Graphique en anneau"),
                    ("radar", "Graphique radar"),
                    ("histogram", "Histogramme"),
                    ("heatmap", "Carte de chaleur"),
                    ("box", "Boîte à moustaches"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="downloads_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="height",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="tags",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="width",
            field=models.PositiveIntegerField(default=800),
        ),
        migrations.AlterModelTable(
            name="visualization", table="analytics_visualization",
        ),
        migrations.AddField(
            model_name="dataanalysisquery",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_queries",
                to="analytics.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.dataset",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="related_analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.analysis",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="related_visualization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.visualization",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="analytics.chatsession",
            ),
        ),
    ]
