# Generated by Django 4.2.7 on 2025-10-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_chatanalyticspreset_chatmessage_chatsession_and_more"),
    ]

    operations = []
