# Generated by Django 4.2.7 on 2025-10-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_auto_20251002_1605"),
    ]

    operations = []
